matching/urls.py
from django.urls import path
from . import views

app_name = 'matching'

urlpatterns = [
    path('api/like/', views.api_send_like, name='api_send_like'),
    path('api/dislike/', views.api_send_dislike, name='api_send_dislike'),
    path('matching/users/', views.MatchingUsers.as_view(), name='matching_users'),
    path('like/users/', views.LikeUsers.as_view(), name='like_users'),
    path('', views.Top.as_view(), name='top'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('matching.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matching/models.py
from django.conf import settings

register/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    # プロフ画像てきなもの
    image = models.ImageField('画像1', blank=True, null=True)

    # いいねしている人達を表現しているフィールド
    # 通常のManyToManyでは、自分がいいねすると相手も自分をいいねする仕様になるため
    # symmetrical=Falseが必要
    likes = models.ManyToManyField('self', blank=True, symmetrical=False, verbose_name='お気に入りの人達')

register/forms.py
from django import forms
from allauth.account.forms import SignupForm as _SignupForm


class SignupForm(_SignupForm):
    # ユーザー登録時に、プロフ画像も含めるためにフィールド追加とメソッド上書き
    image = forms.ImageField(label='画像', required=False)
    
    def save(self, request):
        user = super().save(request)
        user.image = self.cleaned_data['image']
        user.save()
        return user

matching/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import generic
from django.views.decorators.http import require_POST


User = get_user_model()


class Top(LoginRequiredMixin, generic.ListView):
    template_name = 'matching/top.html'
    model = User

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        # 自分は一覧から除外 exclude(id=user.id)
        # 自分が既にいいねした人は一覧から除外 exclude(id__in=user.likes.values('id')
        queryset = queryset.exclude(id=user.id).exclude(id__in=user.likes.values('id'))
        return queryset


@require_POST
@login_required
def api_send_like(request):
    """いいねを押した際に呼ばれる"""
    id = int(request.POST['id'])
    request.user.likes.add(id)
    target = User.objects.get(id=id)

    # 相手も自分をすでに良いねしていた場合、マッチング成立なので、is_matching変数も返す
    is_matching = False
    if request.user.id in target.likes.values_list('id', flat=True):
        is_matching = True

    result = {
        'status': 200,
        'is_matching': is_matching,
    }
    return JsonResponse(result)


@require_POST
@login_required
def api_send_dislike(request):
    """いいねを取り消した場合に呼ばれる"""
    id = int(request.POST['id'])
    request.user.likes.remove(id)

    result = {
        'status': 200,
    }
    return JsonResponse(result)


class MatchingUsers(LoginRequiredMixin, generic.ListView):
    template_name = 'matching/matching_users.html'
    model = User

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        # 自分「を」いいねしている filter(likes__in=[user.id])
        # 自分「が」いいねしている filter(id__in=user.likes.values('id')
        queryset = queryset.filter(likes__in=[user.id]).filter(id__in=user.likes.values('id'))
        return queryset


class LikeUsers(LoginRequiredMixin, generic.ListView):
    template_name = 'matching/like_users.html'
    model = User

    def get_queryset(self):
        queryset = super().get_queryset()
        user = self.request.user
        # 自分がいいねしている人たち
        queryset = queryset.filter(id__in=user.likes.values('id'))
        return queryset

register/views.py
from django.shortcuts import render

# Create your views here.

matching/templates/matching/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>マッチングトップ</title>
    <link rel="stylesheet" href="{% static 'matching/style.css' %}" />
  </head>

  <body>
    <div id="js-toast" class="toast">トースト</div>

    <header id="header">
      <div class="container" id="header-inner">
        <h1 id="title">
          <a href="{% url 'matching:top' %}">Title</a>
        </h1>
        <ul id="menu">
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'matching:matching_users' %}">matched</a>
          </li>
          <li>
            <a href="{% url 'matching:like_users' %}">liked</a>
          </li>
          <li>
            <a href="{% url 'account_logout' %}">logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </header>

    <div class="container">{% block content %}{% endblock %}</div>

    <script src="{% static 'matching/main.js' %}"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

matching/templates/matching/like_users.html
{% extends 'matching/base.html' %}
{% load static %}
{% block content %}

{% for user in user_list %}
<div class="row">
    {% if user.image %}
    <img src="{{ user.image.url }}" class="image1">
    {% else %}
    <img src="{% static 'matching/noimage.png' %}" class="image1">
    {% endif %}

    <div class="right">
        <span class="name">{{ user.username }}</span>
        <button type="button" data-id="{{ user.id }}" class="like">
            <svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 100 100">
                <path stroke="#ff00ba" fill="#333" stroke-width="5"
                    d="M 8,30 A 21,21 0,0,1 50,30 A 21,21 0,0,1 92,30 Q 94.43, 61.91 50,81 Q 5.57, 61.91 8,30 z" />
            </svg>

        </button>

    </div>

</div>
{% endfor %}

<script>
    for (const button of document.getElementsByClassName('like')) {
        button.addEventListener('click', () => {
            fetch(`/api/dislike/`, {
                    method: 'POST',
                    body: `id=${button.dataset.id}`,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                        'X-CSRFToken': csrftoken,
                    },
                })
                .then((response) => response.json())
                .then((data) => {
                    button.parentNode.parentNode.remove()
                    showToast('error', 'お気に入りを解除しました！')
                })
        })
    }
</script>

{% endblock %}

matching/templates/matching/matching_users.html
{% extends 'matching/base.html' %}
{% load static %}
{% block content %}

{% for user in user_list %}
<div class="row">
    {% if user.image %}
    <img src="{{ user.image.url }}" class="image1">
    {% else %}
    <img src="{% static 'matching/noimage.png' %}" class="image1">
    {% endif %}

    <div class="right">
        <span class="name">{{ user.username }}</span>
        <span class="email">{{ user.email }}</span>
        <button type="button" data-id="{{ user.id }}" class="like">
            <svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 100 100">
                <path stroke="#ff00ba" fill="#333" stroke-width="5"
                    d="M 8,30 A 21,21 0,0,1 50,30 A 21,21 0,0,1 92,30 Q 94.43, 61.91 50,81 Q 5.57, 61.91 8,30 z" />
            </svg>

        </button>

    </div>

</div>
{% endfor %}

<script>
    for (const button of document.getElementsByClassName('like')) {
        button.addEventListener('click', () => {
            fetch(`/api/dislike/`, {
                    method: 'POST',
                    body: `id=${button.dataset.id}`,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                        'X-CSRFToken': csrftoken,
                    },
                })
                .then((response) => response.json())
                .then((data) => {
                    button.parentNode.parentNode.remove()
                    showToast('error', 'マッチを解除しました！')
                })
        })
    }
</script>

{% endblock %}

matching/templates/matching/top.html
{% extends 'matching/base.html' %}
{% load static %}

{% block content %}
{% for user in user_list %}
<div class="row">
    {% if user.image %}
    <img src="{{ user.image.url }}" class="image1">
    {% else %}
    <img src="{% static 'matching/noimage.png' %}" class="image1">
    {% endif %}

    <div class="right">
        <span class="name">{{ user.username }}</span>
        <button type="button" data-id="{{ user.id }}" class="like">
            <svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 100 100">
                <path stroke="#ff00ba" fill="#ff00ba" stroke-width="5"
                    d="M 8,30 A 21,21 0,0,1 50,30 A 21,21 0,0,1 92,30 Q 94.43, 61.91 50,81 Q 5.57, 61.91 8,30 z" />
            </svg>

        </button>
    </div>

</div>

{% endfor %}
{% endblock %}


{% block extra_js %}
<script>
    for (const button of document.getElementsByClassName('like')) {
        button.addEventListener('click', () => {
            fetch(`/api/like/`, {
                    method: 'POST',
                    body: `id=${button.dataset.id}`,
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                        'X-CSRFToken': csrftoken,
                    },
                })
                .then((response) => response.json())
                .then((data) => {
                    button.parentNode.parentNode.remove()

                    if (data['is_matching']) {
                        showToast('success', 'マッチ成立しました！')
                    } else {
                        showToast('success', 'お気に入りしました！！')
                    }
                })
        })
    }
</script>
{% endblock %}